@startuml

skinparam {
  Style StrictUML
  SequenceStereotype {
    Font {
      Size 10
      Style plain
    }
  }
}

actor "User" as user
participant "MainMenu" as menu <<form>>
participant "productForm : AddNewProductForm" as form <<form>>
participant "productDAO : ProductCollectionsDAO" as dao  <<dao>>
participant "product : Product" as product <<domain>> 

user -> menu : click "Add a new Product"
menu++

menu -> form : displayForm()
form++

user -> form : Type in ID
user -> form : Type in name
user -> form : Type in description
user -> form : Clicks on category combobox

form -> dao : getCategories() 
dao++
return categories

user -> form : enters in price
user -> form : enters in quantity

user -> form : click "save"
create product
form -> product : <<construct from form data>>

form -> dao : saveProduct(product)
dao++
return

return
@enduml
